// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-j6gudNqCozTW9P5jyNVQ_8ONZBhJTQ',
    appId: '1:1066538231930:web:22176620ecec5bfab673c3',
    messagingSenderId: '1066538231930',
    projectId: 'sprylife-41e5a',
    authDomain: 'sprylife-41e5a.firebaseapp.com',
    storageBucket: 'sprylife-41e5a.appspot.com',
    measurementId: 'G-N9QLCQD31Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrS3DTYs1-OOjB6tBgMabdDx97liAdRY',
    appId: '1:1066538231930:android:bf1acd5ca7fe7cbdb673c3',
    messagingSenderId: '1066538231930',
    projectId: 'sprylife-41e5a',
    storageBucket: 'sprylife-41e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4uqWFIkd6EcsK785xYME3gXH-IEyPxc',
    appId: '1:1066538231930:ios:622f4f642fd66209b673c3',
    messagingSenderId: '1066538231930',
    projectId: 'sprylife-41e5a',
    storageBucket: 'sprylife-41e5a.appspot.com',
    iosBundleId: 'br.com.sprylife.sprylife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO4uqWFIkd6EcsK785xYME3gXH-IEyPxc',
    appId: '1:1066538231930:ios:622f4f642fd66209b673c3',
    messagingSenderId: '1066538231930',
    projectId: 'sprylife-41e5a',
    storageBucket: 'sprylife-41e5a.appspot.com',
    iosBundleId: 'br.com.sprylife.sprylife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK-j6gudNqCozTW9P5jyNVQ_8ONZBhJTQ',
    appId: '1:1066538231930:web:4781dfc59336ba98b673c3',
    messagingSenderId: '1066538231930',
    projectId: 'sprylife-41e5a',
    authDomain: 'sprylife-41e5a.firebaseapp.com',
    storageBucket: 'sprylife-41e5a.appspot.com',
    measurementId: 'G-2GGY7MWRF1',
  );
}
